### ISSUE TITLE
Can't run NFT Demo

### ISSUE THREAD

**Issue by tobiaslins** [LiskHQ/lisk-sdk-examples#109]
I just tried running the current development branch and the backend couldn't start.

```
tobiaslins@Tobiass-MacBook-Pro ~/D/l/t/n/blockchain_app> node index.js
17:08:17 INFO lisk-framework: Starting the app - nft-app (module=lisk:app)
17:08:17 INFO lisk-framework: If you experience any type of error, please open an issue on Lisk GitHub: https://github.com/LiskHQ/lisk-sdk/issues (module=lisk:app)
17:08:17 INFO lisk-framework: Contribution guidelines can be found at Lisk-sdk: https://github.com/LiskHQ/lisk-sdk/blob/development/docs/CONTRIBUTING.md (module=lisk:app)
17:08:17 INFO lisk-framework: Booting the application with Lisk Framework(2.1.0) (module=lisk:app)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (42581)
    at writeFile (fs.js:1385:5)
    at go$writeFile (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/graceful-fs/graceful-fs.js:139:14)
    at Object.writeFile (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/graceful-fs/graceful-fs.js:136:12)
    at /Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/universalify/index.js:8:12
    at new Promise (<anonymous>)
    at Object.writeFile (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/universalify/index.js:7:14)
    at Application._validatePidFile (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/lisk-framework/dist-node/application.js:304:18)
    at async Application.run (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/lisk-framework/dist-node/application.js:123:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}
17:08:17 INFO lisk-framework: Application shutdown started (module=lisk:app)
{
 "errorCode": 0,
 "message": "process.exit"
}
17:08:17 FATAL lisk-framework: Application shutdown failed (module=lisk:app)
Message: Cannot read property 'publish' of undefined
 Trace: TypeError: Cannot read property 'publish' of undefined
    at Application.shutdown (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/lisk-framework/dist-node/application.js:149:27)
    at async handleShutdown (/Users/tobiaslins/Downloads/lisk-sdk-examples-development 3/tutorials/nft/blockchain_app/node_modules/lisk-framework/dist-node/application.js:25:9)
```

This seems strange to me 
```
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (42581)
```

Any ideas why? :)

Using Node v14.8.0 on MacOS 11.2.3

**Comment by tobiaslins** [comment]
Solved by downgrading to Node 12!
