### ISSUE TITLE
Inicialization of hello_world/react-client

### ISSUE THREAD

**Issue by vinicamposdev** [LiskHQ/lisk-sdk-examples#96]
Hi everyone!

I'm newbie in this enviroment and this is my fisrt project with the sdk. I achieve the full installation of hello_world/blockchain_app. So I continue the [tutorial](https://lisk.io/documentation/lisk-sdk/tutorials/hello-world.html) and try to run hello_world/react-client. After I make a **npm install**, I get this error when trying to make **npm start**:

```

> lisk_passphrase@1.0.0 start /home/lisk/lisk-sdk-examples/hello_world/react-client
> webpack serve --mode development --open --hot --port 8989

ℹ ｢wds｣: Project is running at http://localhost:8989/
ℹ ｢wds｣: webpack output is served from undefined
ℹ ｢wds｣: Content not from webpack is served from /home/lisk/lisk-sdk-examples/hello_world/react-client
ℹ ｢wds｣: 404s will fallback to /index.html
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn --hot ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn --hot',
  path: '--hot',
  spawnargs: [ 'http://localhost:8989/' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lisk_passphrase@1.0.0 start: `webpack serve --mode development --open --hot --port 8989`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lisk_passphrase@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

This is related about my lisk-core setup or I missing something else?

**Comment by vinicamposdev** [comment]
I removed --open from start script in package.json and works for me.
